name: Validate Raito SDK
run-name: Validation of Raito SDK
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: true
          cache-dependency-path: go.sum

      - name: Mod Tidy
        run: go mod tidy

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2

      - name: Build
        run: go build ./...

#      - name: Test
#        run: make test
#
#      - uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: ./coverage.txt